echo Running black formatter...
black *.py environment/ reverie/
echo
echo Running djLint formatter...
djlint --quiet --profile=django --reformat --format-js --use-gitignore --extend-exclude=environment/frontend_server/static_dirs environment/ reverie/
